<?php
require 'vendor/autoload.php';
$queue = 'check_url';
$connection = new \PhpAmqpLib\Connection\AMQPConnection('localhost', 5672, 'guest', 'secret2005');
$channel = $connection->channel();
$channel->queue_declare($queue, false, true, false, false);

$msgs = array(
'http://imgur.com/user/FelicityLyman605',
'http://felicitylyman605.skyrock.com/',
'http://www.plurk.com/FelicityLyman605',
'http://www.feedspot.com/u/33db731ab557',
'https://www.reddit.com/user/JackNellsen111',
'http://lawerencegkrk.hazblog.com/Primer-blog-b1/-b1-p359.htm',
'http://patrickuwsn.sosblogs.com/The-first-blog-b1/-b1-p208.htm',
'http://felicitylyman605.soup.io/',
'https://twitter.com/FelicityLyman1',
'http://vaughnfcjg.livejournal.com/',
'http://www.tagged.com/home.html?dataSource=Feed&ll=nav',
'http://www.hi5.com/home.html?dataSource=Explore&ll=nav',
'https://delicious.com/greatone22',
'https://plus.google.com/107921401324873352006/posts',
'http://anthonyranl.hazblog.com/',
'http://edmundoehts.sosblogs.com/The-first-blog-b1/-b1-p187.htm',
'https://www.facebook.com/profile.php?id=100010632693973',
'http://gilbertxolw.sosblogs.com/The-first-blog-b1/-b1-p210.htm',
'http://desmondpckm.hazblog.com/',
'https://www.diigo.com/profile/FelicityLyman605',
'http://emmittkxim.sosblogs.com/The-first-blog-b1/-b1-p239.htm',
'http://patrickuwsn.sosblogs.com/The-first-blog-b1/-b1-p209.htm',
'http://gilbertxolw.sosblogs.com/The-first-blog-b1/-b1-p211.htm',
'https://www.tumblr.com/blog/jacknellsen111',
'http://briggsqoou.livejournal.com/5225.html',
'https://stevenbdcl.wordpress.com/2015/11/05/%EF%BB%BF-2/',
'http://robbinsqszm.blog.com/2015/11/05/﻿-3/',
'http://stuartdjxm.hazblog.com/',
'http://martymcsa.sosblogs.com/The-first-blog-b1/-b1-p179.htm',
'http://lawerencegkrk.hazblog.com/Primer-blog-b1/-b1-p360.htm',
'http://benitohtel.sosblogs.com/The-first-blog-b1/-b1-p222.htm',
'https://www.pinterest.com/jacknellsen111/',
'http://edmundoehts.sosblogs.com/The-first-blog-b1/-b1-p188.htm',
'http://valdezggvk.hazblog.com/',
'https://www.rebelmouse.com/dominiquezeyt/1439686116.html',
'https://rhodesfqxe.wordpress.com/2015/11/05/%EF%BB%BF-3/',
'https://www.facebook.com/Felicity-Lyman-656979877750552/timeline/',
'http://farmerdawk.sosblogs.com/The-first-blog-b1/-b1-p196.htm',
'http://cyrusjpcj.hazblog.com/Primer-blog-b1/-b1-p222.htm',
'http://jaybhgp.sosblogs.com/The-first-blog-b1/-b1-p165.htm',
'http://williamsontvux.hazblog.com/',
'http://merrillpvge.blog.com/2015/11/05/﻿-2/',
'https://www.rebelmouse.com/sangtfbp/1439687642.html',
'https://www.rebelmouse.com/sangtfbp/1439691835.html',
'http://calvinoesu.hazblog.com/',
'http://vaughngvkl.hazblog.com/',
'http://vincentiqgs.hazblog.com/',
'http://rosendolmde.hazblog.com/',
'http://gerardgtli.hazblog.com/',
'http://allendxax.hazblog.com/',
'https://www.rebelmouse.com/kendrickwets/1439694625.html',
'https://harrisonrymg.wordpress.com/2015/11/05/%EF%BB%BF-2/',
'http://willyazxo.bravesites.com',
'http://gerryfkuq.blog.com/2015/11/05/﻿-2/',
'http://stonearlu.blog.com/2015/11/05/﻿-2/',
'http://stonearlu.blog.com/2015/11/05/﻿-3/',
'http://www.journalhome.com/marymrmm/1307585/65279.html',
'http://artcoso.sosblogs.com/The-first-blog-b1/yes-It-Is-Doable-To-Be-Both-An-Introvert-And-An-Extravert-b1-p161.htm',
'http://felicitylyman605.skyrock.com/',
'http://www.plurk.com/FelicityLyman605',
'http://imgur.com/user/FelicityLyman605',
'http://www.feedspot.com/u/33db731ab557',
'https://www.facebook.com/profile.php?id=100010632693973',
'http://perrylhyn.sosblogs.com/The-first-blog-b1/the-Quest-To-Be-Understood-b1-p122.htm',
'https://www.reddit.com/user/JackNellsen111',
'http://erasmobvow.livejournal.com/3890.html',
'https://twitter.com/FelicityLyman1',
'https://delicious.com/greatone22',
'https://www.pinterest.com/jacknellsen111/',
'http://www.tagged.com/home.html?dataSource=Feed&ll=nav',
'http://www.hi5.com/home.html?dataSource=Explore&ll=nav',
'http://noekjjh.livejournal.com/4002.html',
'https://plus.google.com/107921401324873352006/posts',
'http://stanfordffgn.hazblog.com/',
'https://heathiydb.wordpress.com/2015/11/05/%EF%BB%BFlife-in-the-meadow/',
'https://www.facebook.com/Felicity-Lyman-656979877750552/timeline/',
'https://www.diigo.com/profile/FelicityLyman605',
'https://www.tumblr.com/blog/jacknellsen111',
'http://daltonbzzo.sosblogs.com/The-first-blog-b1/how-To-Make-Cash-Out-Of-Nothing-b1-p107.htm',
'http://lelandfufk.sosblogs.com/The-first-blog-b1/you-Wanna-Promote-Me-Something-On-Facebook-I-m-Cool-With-That-b1-p167.htm',
'http://wrightnqsb.hazblog.com/Primer-blog-b1/the-Quest-To-Be-Understood-b1-p95.htm',
'http://erasmobvow.livejournal.com/3834.html',
'http://faustinosoye.sosblogs.com/The-first-blog-b1/sure-It-s-Attainable-To-Be-Both-An-Introvert-And-An-Extravert-b1-p160.htm',
'https://www.rebelmouse.com/cooksexn/1439639805.html',
'http://swansoncrtp.hazblog.com/',
'http://felicitylyman605.soup.io/',
'http://camerondhcd.blog.com/2015/11/05/﻿yes-its-doable-to-be-both-an-introvert-and-an-extravert/',
'http://sebastianpwzm.hazblog.com/',
'https://eltoncfdv.wordpress.com/2015/11/05/%EF%BB%BFlife-in-the-meadow/',
'http://artcoso.sosblogs.com/The-first-blog-b1/yes-It-s-Attainable-To-Be-Each-An-Introvert-And-An-Extravert-b1-p162.htm',
'http://brendonbicb.blog.com/2015/11/05/﻿the-quest-to-be-understood/',
'http://wardwniv.edublogs.org/2015/11/05/%ef%bb%bfare-you-a-shy-introvert-take-this-quiz-and-find-out/',
'http://blackwellboze.hazblog.com/',
'http://perrylhyn.sosblogs.com/The-first-blog-b1/are-You-A-Shy-Introvert-Take-This-Quiz-And-Find-Out-b1-p123.htm',
'http://everettesruj.sosblogs.com/The-first-blog-b1/the-Quest-To-Be-Understood-b1-p120.htm',
'http://wrightnqsb.hazblog.com/Primer-blog-b1/life-In-The-Meadow-b1-p94.htm',
'http://www.purevolume.com/tylerxiou/posts/11711049/%EF%BB%BFyes%2C+It%27s+Attainable+To+Be+Each+An+Introvert+And+An+Extravert',
'http://josephhivp.hazblog.com/',
'http://faustinosoye.sosblogs.com/The-first-blog-b1/are-You-A-Shy-Introvert-Take-This-Quiz-And-Find-Out-b1-p161.htm',
'http://kipnzkj.edublogs.org/2015/11/05/%ef%bb%bflife-in-the-meadow/',
'http://francescojmqm.blog.com/2015/11/05/﻿are-you-a-shy-introvert-take-this-quiz-and-discover-out/',
'http://derrickhxfw.sosblogs.com/The-first-blog-b1/sure-It-Is-Possible-To-Be-Each-An-Introvert-And-An-Extravert-b1-p113.htm',
'http://malcolmpomy.hazblog.com/',
'http://frenchjllb.sosblogs.com/The-first-blog-b1/how-To-Make-Cash-Out-Of-Nothing-b1-p147.htm',
'http://louieyypf.blog.com/2015/11/05/﻿life-in-the-meadow/',
'http://brendonbicb.blog.com/2015/11/05/﻿sure-its-doable-to-be-each-an-introvert-and-an-extravert/',
'http://timothycobl.blog.com/2015/11/05/﻿yes-it-is-doable-to-be-both-an-introvert-and-an-extravert/',
'http://gregkpbk.sosblogs.com/The-first-blog-b1/moonflowerdragon-b1-p120.htm',
'https://julesaiwp.edublogs.org/wp-admin/post.php',
'http://julesaiwp.edublogs.org/2015/11/05/%ef%bb%bfare-you-a-shy-introvert-take-this-quiz-and-find-out/',
'http://frenchjllb.sosblogs.com/The-first-blog-b1/the-Best-And-Worst-Time-To-Promote-A-House-Plus-Residence-Staging-Suggestions-photos-b1-p148.htm',
'http://noekjjh.livejournal.com/4235.html',
'http://hoseavxcs.sosblogs.com/The-first-blog-b1/life-In-The-Meadow-b1-p123.htm',
'http://noblebkqe.sosblogs.com/The-first-blog-b1/create-On-A-Regular-Basis-b1-p162.htm',
'http://gregkpbk.sosblogs.com/The-first-blog-b1/create-Everyday-b1-p119.htm',
'http://cliftonmooe.hazblog.com/',
'http://www.journalhome.com/roderickadet/1307544/65279life-in-the-meadow.html',
'http://www.purevolume.com/tylerxiou/posts/11711050/%EF%BB%BFyes%2C+It+Is+Possible+To+Be+Both+An+Introvert+And+An+Extravert',
'http://kevenplwv.blog.com/2015/11/05/﻿sure-it-is-potential-to-be-each-an-introvert-and-an-extravert/',
'http://hassanxfsi.sosblogs.com/The-first-blog-b1/life-In-The-Meadow-b1-p111.htm',
'http://www.journalhome.com/roderickadet/1307543/65279the-quest-to-be-understood.html',
'http://www.journalhome.com/honguikj/1307539/65279life-in-the-meadow.html',
'http://wardocpy.sosblogs.com/The-first-blog-b1/yes-It-s-Attainable-To-Be-Each-An-Introvert-And-An-Extravert-b1-p114.htm',
'http://www.blackplanet.com/your_page/blog/manage/posting_list.html?pp=1',
'http://domingowpuw.sosblogs.com/The-first-blog-b1/the-Quest-To-Be-Understood-b1-p14.htm',
'http://lelandfufk.sosblogs.com/The-first-blog-b1/how-To-Make-Money-Out-Of-Nothing-b1-p168.htm',
'http://domingowpuw.sosblogs.com/The-first-blog-b1/are-You-A-Shy-Introvert-Take-This-Quiz-And-Discover-Out-b1-p15.htm',
'https://www.rebelmouse.com/cooksexn/1439639856.html',
'http://lannytaez.blog.com/2015/11/05/﻿how-to-make-cash-out-of-nothing/',
'https://salvadormfdr.wordpress.com/2015/11/05/%EF%BB%BFcreate-everyday/',
'http://gregjbzm.livejournal.com/3574.html',
'https://shadiudt.wordpress.com/2015/11/05/%EF%BB%BFmoonflowerdragon/',
'http://www.journalhome.com/honguikj/1307546/65279create-everyday.html',
'https://shadiudt.wordpress.com/2015/11/05/%EF%BB%BFyou-wanna-promote-me-one-thing-on-fb-i-am-cool-with-that/',
'http://kevinwwhd.blog.com/2015/11/05/﻿how-to-make-cash-out-of-nothing/',
'https://www.rebelmouse.com/roderickvfcx/1439640233.html',
'https://www.rebelmouse.com/dyertbqg/1439640225.html',
'http://orlandolkqi.blog.com/2015/11/05/﻿the-finest-and-worst-time-to-sell-a-home-plus-house-staging-ideas-images/',
'http://kraigfbjs.hazblog.com/',
'http://camerondhcd.blog.com/2015/11/05/﻿sure-it-is-attainable-to-be-both-an-introvert-and-an-extravert/',
'http://louieyypf.blog.com/2015/11/05/﻿6-myths-about-introverts-to-cease-believing/',
'http://numbersomei.edublogs.org/2015/11/05/%ef%bb%bfmoonflowerdragon/',
'http://www.purevolume.com/marcusqjps/posts/11711078/%EF%BB%BFyou+Wanna+Promote+Me+Something+On+Fb%3F+I%27m+Cool+With+That',
'http://hoseavxcs.sosblogs.com/The-first-blog-b1/yes-It-s-Possible-To-Be-Each-An-Introvert-And-An-Extravert-b1-p124.htm',
'http://robtwqmb.hazblog.com/',
'http://grosszkgf.sosblogs.com/The-first-blog-b1/sure-It-Is-Attainable-To-Be-Both-An-Introvert-And-An-Extravert-b1-p97.htm',
'http://alonsohosm.hazblog.com/Primer-blog-b1/life-In-The-Meadow-b1-p102.htm',
'http://alonsohosm.hazblog.com/Primer-blog-b1/life-In-The-Meadow-b1-p101.htm',
'http://erwinftwe.sosblogs.com/The-first-blog-b1/create-Everyday-b1-p100.htm',
'http://jonaszcsj.sosblogs.com/The-first-blog-b1/the-Greatest-And-Worst-Time-To-Promote-A-House-Plus-House-Staging-Ideas-photos-b1-p95.htm',
'http://issackzmv.blog.com/2015/11/05/﻿6-myths-about-introverts-to-cease-believing/',
'http://woodztgw.hazblog.com/',
'http://domingomrye.hazblog.com/'
);
// shuffle($msgs);
$order_data_prefix = "3333_25w_";

foreach($msgs as $data) {
    $msg = new \PhpAmqpLib\Message\AMQPMessage($order_data_prefix . $data, array(
        'delivery_mode' => 2,
        'priority' => 1,
        'timestamp' => time(),
        'expiration' => strval(1000 * (strtotime('+1 day midnight') - time() - 1))
    ));
    $channel->basic_publish($msg, '', $queue);
    echo ' [>] "' . $order_data_prefix . $data . '" sent' . PHP_EOL;
}
$channel->close();
$connection->close();